[book]
title = "药娘的天空"
authors = ["乱世银娘"]
language = "zh-CN"

[output.html]
curly-quotes = true
additional-css = ["styles/text.css", "styles/title.css", "theme/navigation.css"]
no-section-label = true
header-link = false
git-repository-url = "https://github.com/Zh40Le1ZOOB/YaoNiangDeTianKong-Fix"
edit-url-template = "https://github.com/Zh40Le1ZOOB/YaoNiangDeTianKong-Fix/edit/main/{path}"
site-url = "/YaoNiangDeTianKong-Fix/"

[output.html.fold]
enable = true

[output.html.search]
limit-results = 1000

[output.epub]
additional-css = ["styles/text.css", "styles/title.css"]
use-default-css = false
cover-image = "images/cover.jpg"
no-section-label = true
curly-quotes = true
