name: Build

on:
  push:
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install mdBook
        uses: baptiste0928/cargo-install@main
        with:
          crate: mdbook
          git: https://github.com/Zh40Le1ZOOB/mdBook
          features: zh

      - name: Install mdbook-epub
        uses: baptiste0928/cargo-install@main
        with:
          crate: mdbook-epub
          git: https://github.com/Michael-F-Bryan/mdbook-epub

      - name: Install mdbook-pdf
        uses: baptiste0928/cargo-install@main
        with:
          crate: mdbook-pdf

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup Pages
        uses: actions/configure-pages@main

      - name: Add version info
        run: echo -e "\n\n## 版本信息\n\n\`\`\`\n提交 SHA：$GITHUB_SHA\n构建时间：$(TZ=Asia/Shanghai date -Iseconds)\n\`\`\`" >> src/text/README.md

      - name: Build
        run: |
          mdbook build
          mv ./book/epub/*.epub ./book/epub/药娘的天空-$GITHUB_SHA.epub
          mv ./book/pdf/*.pdf ./book/pdf/药娘的天空-$GITHUB_SHA.pdf

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: ./book/html/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main

      - name: Upload EPUB artifact
        uses: actions/upload-artifact@main
        with:
          name: EPUB
          path: ./book/epub/*.epub

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@main
        with:
          name: PDF
          path: ./book/pdf/*.pdf
